In [9]:
import numpy as np
arch = np.load("arch_parameters_history_imagenet.npy")

In [10]:
arch.shape

(2, 2, 14, 8)

In [12]:
print(arch[-1])

[[[-1000. -1000. -1000.     0.     0.     0.     0.     0.]
  [-1000.     0.     0. -1000. -1000.     0.     0.     0.]
  [-1000.     0.     0. -1000. -1000.     0.     0.     0.]
  [-1000. -1000.     0.     0.     0.     0.     0. -1000.]
  [-1000.     0. -1000.     0.     0.     0.     0. -1000.]
  [-1000. -1000.     0.     0. -1000.     0.     0.     0.]
  [-1000.     0. -1000.     0.     0.     0. -1000.     0.]
  [-1000.     0.     0. -1000. -1000.     0.     0.     0.]
  [-1000. -1000.     0.     0.     0.     0.     0. -1000.]
  [-1000.     0.     0.     0.     0. -1000. -1000.     0.]
  [-1000.     0.     0.     0.     0. -1000.     0. -1000.]
  [-1000.     0.     0.     0. -1000.     0.     0. -1000.]
  [-1000. -1000.     0.     0.     0.     0. -1000.     0.]
  [-1000. -1000.     0.     0.     0.     0.     0. -1000.]]

 [[-1000. -1000. -1000.     0.     0.     0.     0.     0.]
  [-1000.     0.     0. -1000.     0.     0. -1000.     0.]
  [-1000.     0.     0.     0.     0. 

In [ ]:
{lambda: [index, cifar10_top1_acc, latency]}
{0.1: [3424, 93.5, 23.242],
 0.2: [3424, 93.5, 23.242],
 0.3: [3424, 93.5, 23.242],
 0.4: [3424, 93.5, 23.242],
 0.5: [12115, 92.2, 17.56],
 0.6: [12115, 92.2, 17.56],
 0.7: [14574, 92.32, 17.56],
 0.8: [6683, 88.51, 10.94],
 0.9: [1835, 54.30, 0.85],
 }